# Site settings
domain: "2RD.top"
url: "https://2rd.top"

# main settings
main_title: "Linktree"
main_description: "รวมลิงค์โปรไฟล์โซเชียลมีเดียทั้งหมดของผม"
main_ogm: "/images/2rd_ogm.png"

# mcpe settings
mcpe_url: "/mcpe"
mcpe_title: "ม็อดไมน์คราฟต์เบดร็อก"
mcpe_description: "🤣 ทำตามอารมณ์ ไม่มีอารมณ์ก็ไม่ทำ 🤣"
mcpe_ogm: "/images/mcpe_ogm.png"

# hytale settings
hytale_url: "/hytale"
hytale_title: "ม็อดไฮเทล"
hytale_description: "🤣 ทำตามอารมณ์ ไม่มีอารมณ์ก็ไม่ทำ 🤣"
hytale_ogm: "/images/hytale_ogm.png"

# 404 settings
404_title: "404 PAGE NOT FOUND"
404_description: "ไซต์ที่กําหนดค่าตามที่อยู่นี้ไม่ มีไฟล์ที่ร้องขอ"

# User settings
username: "2RD"
email: "contact@2rd.top"
footer: "<p class='footer'>Built by <a href='URL_PLACEHOLDER' target='_top' rel='noopener'>USER_PLACEHOLDER</a> and <a href='https://littlelink.io/' target='_blank' rel='noopener'>LittleLink</a>.</p>"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

